apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: robomart
spec:
  selector:
    project: {{ .Values.deployment.project }}
    component: {{ .Values.deployment.component }}
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080