apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: robomart
spec:
  selector:
    project: robomart
    component: mongodb
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017