apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: robomart
spec:
  selector:
    project: robomart
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306 # container port