apiVersion: v1
kind: Service
metadata:
  name: redis 
  namespace: robomart
spec:
  selector:
    project: {{ .Values.deployment.project }}
    component: {{ .Values.deployment.component }}
    tier: db
  ports:
  - protocol: TCP 
    port: 6379
    targetPort: 6379