apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: robomart
spec:
  selector:
    project: robomart
    component: cart
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080