apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: robomart
  # these are replica set labels
  labels:
    project: robomart
    component: rabbitmq
    tier: db
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: robomart
      component: rabbitmq
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        project: robomart
        component: rabbitmq
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: {{ .Values.deployment.imageRepo }}/{{ .Values.deployment.component }}:{{ .Values.deployment.imageVersion }}
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: roboshop
        - name: RABBITMQ_DEFAULT_PASS
          value: roboshop123
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 20
          periodSeconds: 5