apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: robomart
spec:
  selector:
    project: robomart
    component: rabbitmq
    tier: db
  ports:
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port