apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: robomart
spec:
  selector:
    project: robomart
    component: catalogue
    tier: backend
  ports:
  - protocol: TCP 
    port: 8080
    targetPort: 8080